---
title: "Simbius Randomization"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(knitr)
```

<!--### Data Randomization-->

```{r, data, echo = FALSE, results = 'hide'}
simbius <- read.xlsx("../data/simbius.xlsx", 
                     1, 
                     startRow = 2, 
                     endRow = 22, 
                     colIndex = 1:4, 
                     colClasses = rep("character", 6), 
                     encoding = "UTF-8", 
                     stringsAsFactors = FALSE)
str(simbius)
```

```{r, randomization, echo = FALSE, results = 'hide'}
set.seed(73)
N <- nrow(simbius) 
group <- 1 + sample(1:N) %% 2
simbius$group <- factor(group, levels = 1:2, labels = c("red", "black"))
# red.id <- sample(1:N, size = floor(N / 2))
# red.id
# simbius$group <- factor(ifelse((1:N) %in% red.id, "red", "black"), levels = # c("red", "black"))
# black.id <- (1:N)[-red.id]
```

### Randomization Effects

#### 학년 

```{r, year, echo = FALSE}
year.f <- factor(simbius$year, 
                 labels = c("1학년", "2학년"))
kable(table("Group" = simbius$group, 
            "학년" = year.f))
```

#### 성별

```{r, gender, echo = FALSE}
gender.f <- factor(simbius$gender, 
                   labels = c("남", "여"))
kable(table("Group" = simbius$group, 
            "성별" = gender.f))
```

#### 많이 나오는 성씨

```{r, family name, echo = FALSE}
f.name <- substring(simbius$name, 
                    first = 1, 
                    last = 1)
f.name.f <- factor(ifelse(f.name %in% c("김", "이", "박","최"), f.name, "기타"), 
                   levels = c("김", "이", "박", "최", "기타"))
kable(table("Group" = simbius$group, 
            "Family Name" = f.name.f))
```

<!--### List of Group Members-->

```{r, list, echo=FALSE, message=FALSE, results='hide'}
gr.id.o <- order(simbius$group, simbius$school)
id.by.gr <- simbius[gr.id.o, c("group", "school", "name")]
red.names <- id.by.gr[id.by.gr$group == "red", c("school", "name")]
kable(red.names)
black.names <- id.by.gr[id.by.gr$group=="black", c("school", "name")]
kable(black.names)
red.black.df <- data.frame("Red" = red.names, "Black" = black.names, row.names = NULL)
```

<P style="page-break-before: always">

```{r, print_out, echo=FALSE, results = 'asis'}
kable(red.black.df)
```

```{r, save, echo=FALSE, message=FALSE, results='hide'}
# save.image("../R/simbius_data.RData")
```